made a 404 page
MagmaWM/MagmaWM.github.io pull request #18
Opened 2024-04-17 17:36 UTC by killertofus

2024-04-20 03:02 UTC, electron271 requested changes

2024-04-20 03:02 UTC, electron271 commented on 404.html
> +    <link rel="preload" href="/_next/static/css/79ba91c6d57651c5.css" as="style" />
wha

2024-04-20 03:02 UTC, electron271 commented on 404.html
> +    <link rel="preload" href="/_next/static/css/79ba91c6d57651c5.css" as="style" />
we dont use nextjs

2024-04-20 03:02 UTC, electron271 commented on assets/404.css
> +/*
why does the 404 of all things need 1600 lines of css

2024-04-21 03:06 UTC, killertofus commented
now it has less code :)

2024-04-21 03:16 UTC, HackedOS approved these changes
lgtm

2024-04-21 03:18 UTC, HackedOS commented
its not letting me merge?????

2024-04-21 03:21 UTC, electron271 approved these changes
you cant self-review

2024-04-21 03:21 UTC, electron271 commented
no wait nevermind i thought it was your pr

was cause i requested changes

2024-04-21 03:21 UTC, merged